import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);
            double input1 = s.nextDouble();
            double input2 = s.nextDouble();
        
        if (input1>0 && input2 > 0)
        {
            System.out.print(input1 + "-" + input2);
        }
        else
        {
            System.out.print("Invalid Input");
        }
            
    }
}
